[package]
name = "speech-native-platform"
build = "build.rs"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
repository.workspace = true

[dependencies]
async-trait.workspace = true
speech-native-types = { path = "../speech-native-types" }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
avspeechsynthesizer = { package = "avspeechsynthesizer-rs", version = "0.3.7" }
speech = { version = "0.8.7", default-features = false }

[dev-dependencies]
speech-native-router = { path = "../speech-native-router" }

[lints]
workspace = true
